# Form implementation generated from reading ui file 'assets/main.ui'
#
# Created by: PyQt6 UI code generator 6.5.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(287, 346)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.hover_box = QtWidgets.QGraphicsView(parent=self.centralwidget)
        self.hover_box.setObjectName("hover_box")
        self.gridLayout.addWidget(self.hover_box, 1, 1, 1, 1)
        self.hover_input = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.hover_input.setObjectName("hover_input")
        self.gridLayout.addWidget(self.hover_input, 0, 1, 1, 1)
        self.selected_box = QtWidgets.QGraphicsView(parent=self.centralwidget)
        self.selected_box.setObjectName("selected_box")
        self.gridLayout.addWidget(self.selected_box, 3, 1, 1, 1)
        self.selected_input = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.selected_input.setObjectName("selected_input")
        self.gridLayout.addWidget(self.selected_input, 2, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.hex_selected_button = QtWidgets.QPushButton(parent=self.groupBox)
        self.hex_selected_button.setGeometry(QtCore.QRect(10, 50, 61, 32))
        self.hex_selected_button.setObjectName("hex_selected_button")
        self.css_selected_button = QtWidgets.QPushButton(parent=self.groupBox)
        self.css_selected_button.setGeometry(QtCore.QRect(10, 20, 61, 32))
        self.css_selected_button.setObjectName("css_selected_button")
        self.gridLayout.addWidget(self.groupBox, 3, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.hex_hover_button = QtWidgets.QPushButton(parent=self.groupBox_2)
        self.hex_hover_button.setGeometry(QtCore.QRect(10, 50, 61, 32))
        self.hex_hover_button.setObjectName("hex_hover_button")
        self.css_hover_button = QtWidgets.QPushButton(parent=self.groupBox_2)
        self.css_hover_button.setGeometry(QtCore.QRect(10, 20, 61, 32))
        self.css_hover_button.setObjectName("css_hover_button")
        self.gridLayout.addWidget(self.groupBox_2, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 2, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Color Picker"))
        self.label_2.setText(_translate("MainWindow", "Hover"))
        self.hex_selected_button.setText(_translate("MainWindow", "Hex"))
        self.css_selected_button.setText(_translate("MainWindow", "CSS"))
        self.hex_hover_button.setText(_translate("MainWindow", "Hex"))
        self.css_hover_button.setText(_translate("MainWindow", "CSS"))
        self.label.setText(_translate("MainWindow", "Selected Color"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
